config/routes.rb
JoincicAppMt::Application.routes.draw do

  root 'joincics#index'

  resources :joincics, only: [] do
    get 'show_schools', on: :collection
    get 'show_active_students', on: :member
    get 'show_school_students', on: :member
  end

end

app/models/person.rb
class Person < ActiveRecord::Base

  belongs_to :school

  def country
    self.school.country
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/school.rb
class School < ActiveRecord::Base

  belongs_to :country
  has_many :students, class_name: 'Person'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def get_schools
    url = "http://localhost:4000/auxiliar/joincics/show_schools"
    uri = URI.parse(url)
    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Get.new(uri.request_uri)
    # request["Accept"] = "application/vnd.api.akdemia.com+json; version=2"
    response = http.request(request)
    data = JSON.parse(response.body)
    return data
  end

  def get_students(school_id)
    url = "http://localhost:4000/auxiliar/joincics/#{school_id}/get_school_students"
    uri = URI.parse(url)
    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Get.new(uri.request_uri)
    # request["Accept"] = "application/vnd.api.akdemia.com+json; version=2"
    response = http.request(request)
    data = JSON.parse(response.body)
    return data
  end

  def get_active_students(country_id)
    url = "http://localhost:4000/<TO DO>"
    uri = URI.parse(url)
    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)
    data = JSON.parse(response.body)
    return data
  end

end

app/controllers/joincics_controller.rb
class JoincicsController < ApplicationController


  def index
  end

  def show_schools
    @schools = []
    data = get_schools

    data.each do |school_data|
      @schools << School.new(school_data.except('students'))
    end
  end

  def show_school_students
    school_id = params[:id]
    @school = School.find(school_id)
    @students = []

    data = get_students(school_id)
    data.each do |student_data|
      @students << Person.new(student_data.slice('first_name', 'last_name', 'email'))
    end
  end

  def show_active_students
    country_id = params[:id]
    case country_id.to_i
    when 138
      @country_name = "Perú"
    when 186
      @country_name = "USA"
    when 191
      @country_name = "Venezuela"
    end

    @students = []

    # TO DO

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/joincics_helper.rb
module JoincicsHelper
end

app/views/joincics/index.html.haml
%h1
  = "8JOINCIC - Mesa de Trabajo Akdemia"

= link_to "Schools", show_schools_joincics_path
%br/
%br/
= link_to "Active in Perú", show_active_students_joincic_path(138)
%br/
= link_to "Active in USA", show_active_students_joincic_path(186)
%br/
= link_to "Active in Venezuela", show_active_students_joincic_path(191)
%br/

app/views/joincics/show_active_students.html.haml
%h1
  = "8JOINCIC - Mesa de Trabajo Akdemia"

  %h2
    = "Active in #{@country_name}"

%table
  %thead
    %tr
      %th{ style: "width: 150px"}
        = "First Name"
      %th{ style: "width: 150px"}
        = "Last Name"
      %th{ style: "width: 150px"}
        = "Email"
  %tbody
    - @students.each do |student|
      %tr
        %td
          = student.first_name
        %td
          = student.last_name
        %td
          = student.email

app/views/joincics/show_school_students.html.haml
%h1
  = "8JOINCIC - Mesa de Trabajo Akdemia"

%h2
  = "#{@school.name} (#{@school.code})"

%table
  %thead
    %tr
      %th{ style: "width: 150px"}
        = "First Name"
      %th{ style: "width: 150px"}
        = "Last Name"
      %th{ style: "width: 150px"}
        = "Email"
  %tbody
    - @students.each do |student|
      %tr
        %td
          = student.first_name
        %td
          = student.last_name
        %td
          = student.email

app/views/joincics/show_schools.html.haml
%h1 Joincics#show_schools

%table
  %thead
    %tr
      %th{ style: "width: 100px"}
        = "Name"
      %th{ style: "width: 100px"}
        = "Code"
      %th{ style: "width: 100px"}
        = "Private"
  %tbody
    - @schools.each do |school|
      %tr
        %td
          = link_to school.name, show_school_students_joincic_path(school.id)
        %td
          = school.code
        %td
          = school.is_private

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JoincicAppMt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>